services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: lanars
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lanars
    ports:
      - "5555:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
