export const AUTH_SERVICE = 'AUTH_SERVICE';
export const TOKEN_SERVICE = 'TOKEN_SERVICE';
export const AUTH_TOKEN_SERVICE = 'AUTH_TOKEN_SERVICE';
export const AUTH_TOKEN_REPOSITORY = 'AUTH_TOKEN_REPOSITORY';
export const SKIP_AUTH = 'SKIP_AUTH';
